// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kingkey.qn.domain;

import com.kingkey.qn.domain.PartDataOnDemand;
import com.kingkey.qn.domain.Question;
import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect QuestionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QuestionDataOnDemand: @Component;
    
    private Random QuestionDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Question> QuestionDataOnDemand.data;
    
    @Autowired
    private PartDataOnDemand QuestionDataOnDemand.partDataOnDemand;
    
    public Question QuestionDataOnDemand.getNewTransientQuestion(int index) {
        com.kingkey.qn.domain.Question obj = new com.kingkey.qn.domain.Question();
        obj.setComment("comment_" + index);
        obj.setDefaultCompletContent("defaultCompletContent_" + index);
        obj.setFirstLabel("firstLabel_" + index);
        obj.setLastLabel("lastLabel_" + index);
        obj.setOrderNo(new Integer(index));
        obj.setPart(partDataOnDemand.getRandomPart());
        obj.setQuestion("question_" + index);
        obj.setQuestionType(null);
        obj.setRequired(Boolean.TRUE);
        return obj;
    }
    
    public Question QuestionDataOnDemand.getSpecificQuestion(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Question obj = data.get(index);
        return Question.findQuestion(obj.getId());
    }
    
    public Question QuestionDataOnDemand.getRandomQuestion() {
        init();
        Question obj = data.get(rnd.nextInt(data.size()));
        return Question.findQuestion(obj.getId());
    }
    
    public boolean QuestionDataOnDemand.modifyQuestion(Question obj) {
        return false;
    }
    
    public void QuestionDataOnDemand.init() {
        data = com.kingkey.qn.domain.Question.findQuestionEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Question' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.kingkey.qn.domain.Question>();
        for (int i = 0; i < 10; i++) {
            com.kingkey.qn.domain.Question obj = getNewTransientQuestion(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
