// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kingkey.qn.domain;

import com.kingkey.qn.domain.Part;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PartDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PartDataOnDemand: @Component;
    
    private Random PartDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Part> PartDataOnDemand.data;
    
    public Part PartDataOnDemand.getNewTransientPart(int index) {
        com.kingkey.qn.domain.Part obj = new com.kingkey.qn.domain.Part();
        obj.setLabel("label_" + index);
        obj.setOrderNo(new Integer(index));
        obj.setQuestionnaire(null);
        return obj;
    }
    
    public Part PartDataOnDemand.getSpecificPart(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Part obj = data.get(index);
        return Part.findPart(obj.getId());
    }
    
    public Part PartDataOnDemand.getRandomPart() {
        init();
        Part obj = data.get(rnd.nextInt(data.size()));
        return Part.findPart(obj.getId());
    }
    
    public boolean PartDataOnDemand.modifyPart(Part obj) {
        return false;
    }
    
    public void PartDataOnDemand.init() {
        data = com.kingkey.qn.domain.Part.findPartEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Part' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.kingkey.qn.domain.Part>();
        for (int i = 0; i < 10; i++) {
            com.kingkey.qn.domain.Part obj = getNewTransientPart(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
