// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kingkey.qn.domain;

import com.kingkey.qn.domain.QuestionOptionDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionOptionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionOptionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionOptionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: QuestionOptionIntegrationTest: @Transactional;
    
    @Autowired
    private QuestionOptionDataOnDemand QuestionOptionIntegrationTest.dod;
    
    @Test
    public void QuestionOptionIntegrationTest.testCountQuestionOptions() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        long count = com.kingkey.qn.domain.QuestionOption.countQuestionOptions();
        org.junit.Assert.assertTrue("Counter for 'QuestionOption' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFindQuestionOption() {
        com.kingkey.qn.domain.QuestionOption obj = dod.getRandomQuestionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = com.kingkey.qn.domain.QuestionOption.findQuestionOption(id);
        org.junit.Assert.assertNotNull("Find method for 'QuestionOption' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'QuestionOption' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFindAllQuestionOptions() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        long count = com.kingkey.qn.domain.QuestionOption.countQuestionOptions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'QuestionOption', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.kingkey.qn.domain.QuestionOption> result = com.kingkey.qn.domain.QuestionOption.findAllQuestionOptions();
        org.junit.Assert.assertNotNull("Find all method for 'QuestionOption' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'QuestionOption' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFindQuestionOptionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        long count = com.kingkey.qn.domain.QuestionOption.countQuestionOptions();
        if (count > 20) count = 20;
        java.util.List<com.kingkey.qn.domain.QuestionOption> result = com.kingkey.qn.domain.QuestionOption.findQuestionOptionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'QuestionOption' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'QuestionOption' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testFlush() {
        com.kingkey.qn.domain.QuestionOption obj = dod.getRandomQuestionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = com.kingkey.qn.domain.QuestionOption.findQuestionOption(id);
        org.junit.Assert.assertNotNull("Find method for 'QuestionOption' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyQuestionOption(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'QuestionOption' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testMerge() {
        com.kingkey.qn.domain.QuestionOption obj = dod.getRandomQuestionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = com.kingkey.qn.domain.QuestionOption.findQuestionOption(id);
        boolean modified =  dod.modifyQuestionOption(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.kingkey.qn.domain.QuestionOption merged = (com.kingkey.qn.domain.QuestionOption) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'QuestionOption' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", dod.getRandomQuestionOption());
        com.kingkey.qn.domain.QuestionOption obj = dod.getNewTransientQuestionOption(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'QuestionOption' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'QuestionOption' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionOptionIntegrationTest.testRemove() {
        com.kingkey.qn.domain.QuestionOption obj = dod.getRandomQuestionOption();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'QuestionOption' failed to provide an identifier", id);
        obj = com.kingkey.qn.domain.QuestionOption.findQuestionOption(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'QuestionOption' with identifier '" + id + "'", com.kingkey.qn.domain.QuestionOption.findQuestionOption(id));
    }
    
}
